"""empty message

Revision ID: 33784c5c5333
Revises: f425107e9976
Create Date: 2017-02-26 04:06:35.624778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33784c5c5333'
down_revision = 'f425107e9976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
